# This Containerfile is supposed to be run from the
# vdpa-network-binding-plugin repository root dir.
FROM quay.io/centos/centos:stream9 AS builder

WORKDIR /usr/src/vdpa_network_binding_sidecar
RUN dnf update -y && dnf clean all
RUN dnf install -y golang make git

COPY . .
RUN make clean
RUN make SIDECAR_NAME=vdpa-network-binding-sidecar build_sidecar

FROM quay.io/centos/centos:stream9 AS sidecar
RUN dnf update -y && dnf clean all

COPY --from=builder \
    /usr/src/vdpa_network_binding_sidecar/build/vdpa-network-binding-sidecar /.

ENTRYPOINT /vdpa-network-binding-sidecar
